[package]
name = "linux-infrared"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"

[dependencies]
irp = { path = "irp" }
clap = "2.33"
toml = "0.5"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
iocuddle = "0.1.1"
itertools = "0.10"
evdev = { git = "https://github.com/emberian/evdev" }
mio = { version = "0.7", features = [ "os-poll", "os-ext" ] }
libc = "0.2"
nix = "0.21"

[profile.release]
lto = true
