[package]
name = "ir-ctl"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.18"
features = ["lexer"]

[dependencies]
lalrpop-util = "0.18"
num = "0.2.1"
clap = "2.33.0"
toml = "0.5"
serde = "1.0"
regex = "1.3.4"
serde_derive = { version = "1.0" }
bitintr = "0.3.0"
