[package]
name = "ir-ctl"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
clap = "2.33.0"