[package]
name = "ir-ctl"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lrpeg = { git = "https://github.com/seanyoung/lrpeg", branch = "main" }

[dependencies]
num = "0.4"
clap = "2.33.0"
toml = "0.5"
regex = "1"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
bitintr = "0.3.0"
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
unicode-xid = "0.2"
serde_json = "1.0"