[package]
name = "ir"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"

[dependencies]
irp = { path = "irp" }
lirc = { path = "lirc" }
clap = "2.33.0"
toml = "0.5"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
