[package]
name = "ir-ctl"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2018"
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.19"
features = ["lexer"]

[dependencies]
lalrpop-util = "0.19"
num = "0.3"
clap = "2.33.0"
toml = "0.5"
regex = "1.3.4"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
bitintr = "0.3.0"
# quick-xml = { version = "0.20.0", features = [ "serialize" ] }
quick-xml = { path = "../quick-xml", features = [ "serialize" ] }
