[package]
name = "irp"
version = "0.2.0"
authors = ["Sean Young <sean@mess.org>"]
repository = "https://github.com/seanyoung/ir"
edition = "2018"
description = "Infrared IRP encoder"
documentation = "https://docs.rs/irp/"
keywords = [ "IRP", "IR", "infrared", "pronto" ]
build = "build.rs"
readme = "README.md"
license = "MIT"

[build-dependencies]
lrpeg = "0.4"

[dependencies]
num = "0.4"
regex = "1"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
unicode-xid = "0.2"
serde_json = "1.0"
rand = "0.8"
bitvec = "0.22"
