[package]
name = "irp"
version = "0.2.2"
authors = ["Sean Young <sean@mess.org>"]
repository = "https://github.com/seanyoung/cir"
edition = "2021"
description = "Infrared IRP encoder"
documentation = "https://docs.rs/irp/"
keywords = [ "IRP", "IR", "infrared", "pronto" ]
build = "build.rs"
readme = "README.md"
license = "MIT"

[build-dependencies]
lrpeg = "0.4.1"

[dependencies]
num = "0.4"
regex = "1"
serde_derive = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
xml-rs = "0.8"
unicode-xid = "0.2"
bitvec = "1.0"
log = "0.4"

[dev-dependencies]
serde_json = "1.0"
