name: Build tests
on: [push, pull_request]
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust stable
        run: rustup default stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --tests --bins -- -D warnings -D clippy::inconsistent-struct-constructor

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Rust stable
      run: rustup default 1.53.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
